### ISSUE TITLE
Use CI

### ISSUE THREAD

**Issue by pjz** [godaddy/Thespian#13]
I see tox is configured - why not hook this github repo up to travisCI or somesuch to run it automatically?  It would give a bit more feedback about PRs.

**Comment by pjz** [comment]
Oh, and if you want windows testing, there's appveyor.

**Comment by kwquick** [comment]
Unfortunately, testing for Thespian at the present time is oriented more towards verifying actual running behavior instead of isolated and abstracted unit testing (more details here:  
http://godaddy.github.io/Thespian/doc/developer.html#outline-container-sec-2).

The result of this approach is that there is a potential for processes to be leftover and for various collateral failures due to system issues.  There are also spurious and non-deterministic failures in the MultiprocQueue base which may indicate some Queue issues.

End result is that I'd love to use CI but at the present time there is some indeterminism and instability in the testing process that would probably cause CI failures due to edge cases or systemic issues, but would not reflect on the viability of the code for standard functionality.

This is one of the areas for future work (I think I recall mentioning elsewhere that I need a roadmap).  Along with this there is an investigation of switching from nose to pytest (for many reasons, including nose's obsolescence and the ease of using markers in pytest).  The tox file is a legacy element that has not been used in some time and should be removed because it is misleading.  Multi-environment testing *is* performed, but it is largely manual at the present time.

P.S.  Thank you for the information on appveyor.

**Comment by pjz** [comment]
So, the CI roadmap is something like:

 - [ ] switch to pytest
 - [ ] tag unstable tests
 - [ ] use travis-CI and appveyor to run stable tests

?

**Comment by kwquick** [comment]
Essentially, yes.  The middle phase will include additional investigation in the tests providing unstable results to see if something can/should be done.

Just as an example, there's a test that creates 100 actors and verifies that each of them got a unique address value.  The actual address value is dependent on the System Base in use.  For the TCP and UDP multi-process bases, this means that the (ip address + port) is unique.  Under Linux, this test occasionally fails for the UDP multi-process base with two actors seeming to get the same port number.  It's unclear at this point why this is occurring, but this is the type of instability I'm referring to here.

**Comment by pjz** [comment]
Well, honestly, if the goal is 'get CI working', then just knowing they're unstable is the first step.  Once they're marked as such, investigation into if and how to fix them can be done at any later date, without stopping the project from gaining the advantages of running the rest of the tests on every push/PR.

**Comment by kwquick** [comment]
Belatedly closing this issue:  a TravisCI configuration has been setup for Thespian (https://travis-ci.org/kquick/Thespian) with build tags showing the current status on the github page.
