### ISSUE TITLE
Actor Initialization

### ISSUE THREAD

**Issue by kevincolyar** [godaddy/Thespian#18]
Looking for some guidance on initializing an Actor with its internal state.  For example, if I have an Actor that saves messages it receives to a database, what's the best way to pass it the db client it needs?  I've gotten it working instantiating the db client in my Actor's `__init__` but I prefer to pass it in as it will need to work with different db clients.

**Comment by kwquick** [comment]
I would typically recommend having your DB-accessing Actor startup with null credentials.  The startup process would then send an initialization message containing the credential information, or alternatively you could have a "config" Actor (with a globalName so that it is always accessible and a singleton) that the DB-access Actor could ask for the configuration.

The first scenario might look something like this:
```
from thespian.actors import *

class Credentials(object):
    def __init__(self, creds):
        self.credentials = creds

class DBUpdateActor(ActorTypeDispatcher):
    def receiveMsg_Credentials(self, cred_msg, sender):
        self.credentials = cred_msg.credentials
    def receiveMsg_Work(self, work_msg, sender):
        if not getattr(self, 'credentials', None):
            self.send(sender, ErrorMsg('no credentials')
            return
        db.access(self.credentials).update_from(work_msg)

def startup(creds):
    asys = ActorSystem(...)
    dbactor = asys.createActor(DBUpdateActor)
    asys.tell(dbactor, Credentials(creds))
    ...
    result = (asys.ask(dbactor, work, timedelta(seconds=15))
    if isinstance(result, Error):
        ...
```

The second scenario might be something like this:
```
from thespian.actors import *

class Credentials(object):
    def __init__(self, creds):
        self.credentials = creds

class ConfigActor(Actor):
    def receiveMessage(self, message, sender):
        creds = open('secret_credentials.cfg', 'r').read()
        self.send(sender, Credentials(creds))

class DBUpdateActor(ActorTypeDispatcher):
    def __init__(self, *args, **kw):
        super(DBUpdateActor, self).__init__(*args, **kw)
        self.pending_work = []
    def receiveMsg_Credentials(self, cred_msg, sender):
        self.credentials = cred_msg.credentials
        pending = self.pending_work
        self.pending_work = []
        for each in pending:
            self.send(self.myAddress, each)
    def receiveMsg_Work(self, work_msg, sender):
        if not getattr(self, 'credentials', None):
            self.send(self.createActor(ConfigActor, globalName="Config"), "get creds")
            self.pending_work.append(work)
            return
        db.access(self.credentials).update_from(work_msg)

def startup():
    asys = ActorSystem(...)
    cfgactor = asys.createActor(ConfigActor, globalName="Config")
    dbactor = asys.createActor(DBUpdateActor)
    ...
    asys.tell(dbactor, work)
```

These are highly simplistic examples, but demonstrate two fairly different approaches to the issue; there are lots of variations, and things that can be done to make either method more robust, but hopefully this helps answer your initial question.  Let me know if there are more questions or if you would like clarification of the above.

**Comment by kevincolyar** [comment]
Thanks for the examples.  I'll give it a shot.
