### ISSUE TITLE
Pickling error attempting to create 'multiprocxxx' Actor system

### ISSUE THREAD

**Issue by kwadl** [godaddy/Thespian#32]
Hi there

Thanks for releasing what looks like a really promising project. I'm keen to get started with it, but am encountering an issue with starting a 'multiprocTCPBase' Actor system (or any 'multiproc' Actor system) in a Windows environment. It looks like in multiprocCommon.py in _startAdmin (line 102) a reference to the multiprocessing module itself is being passed to a new process as an argument? This seems to lead to a pickling error...
[trace.txt](https://github.com/godaddy/Thespian/files/706904/trace.txt)

**Comment by kwadl** [comment]
Okay, so the attached mods seem to fix this for Python 2.7+Windows, but not sure what the broader implications might be. The mods allow the context to be passed around as a default of None if version 3.4 of multiprocessing is not found (instead of a default reference to the multiprocessing module itself), avoiding the pickling error. Users of the context test for the default and use the multiprocessing module directly if required...
[multiprocCommon.py.txt](https://github.com/godaddy/Thespian/files/706969/multiprocCommon.py.txt)

**Comment by kquick** [comment]
Thanks for the update!  Most of the recent Windows work has been done using 3.5 (python version validation testing normally happens under linux), so it's been a while since I validated the combo of Windows and 2.7 and it looks like a compatibility issue crept in.

Please give me a day or so to run validation of your fix across the other environments, and then I can generate a bugfix release.  In the meantime, I'd love to have you submit your fix as a pull request so you can get proper attribution.

**Comment by kwadl** [comment]
Hope it helps! I'm not too handy with github, so not sure I can master a pull request, but if the mods work for you of course you can incorporate them. Cheers

**Comment by kwquick** [comment]
The mods do work for me as well and tested out on all the environments, so I'll be releasing this shortly.  Thanks again for your contribution!

**Comment by kwquick** [comment]
Fixed in Release 3.6.1 (https://github.com/godaddy/Thespian/releases/tag/thespian-3.6.1)
