### ISSUE TITLE
State

### ISSUE THREAD

**Issue by dkhan11** [godaddy/Thespian#36]
Hi,

First, thank you for this great project!
I'm working with other frameworks like Akka and I'm trying to understand how to manage Actor **state** in this project. Since one Actor is not supposed to update another's state, but is able to modify its own I have several questions:
1. What is the best way to use your API to manage internal Actor state?
2. Can this state long live failures and restarts?

Thanks in advance, 
DD

**Comment by kwquick** [comment]
In Thespian, each Actor is a subclass of the `Actor` base class, and can add state by placing values in local class members.  For example:

    class MyActor(Actor):
        def receiveMessage(self, msg, sender):
            if isinstance(msg, StateUpdate):
                self.my_state = msg

This state is not persisted by default, so any time the Actor is (re)started it has no defined initial state.  There are a couple of ways that you could initialize and persist an Actor's state, including:
* Writing state to a local file that the Actor reads on restart
* Writing state to a database ...
* Writing state to a key/value store (like ZooKeeper, etcd, consuld, etc.)

Also note that the state could be initialized by receiving one or more state messages from a state management Actor instead of directly managing the state in the current Actor.

Thank you for the appreciation and interest in Thespian, and I hope this answer helps you.  Feel free to inquire further if you have more questions (either here or on the mailing list).

**Comment by dkhan11** [comment]
Got it, great answer! It helps and I will try your Actor state Management idea.
Thanks,
DD.
