### ISSUE TITLE
Pending Actor request received for xxxActorClass reqs None from ActorAddr-(TCP|178.79.176.66:38784)

### ISSUE THREAD

**Issue by pjz** [godaddy/Thespian#4]
...what causes this?  I get a bunch in my thespian.log when (I think?) the xxxActorClass is being flooded with messages.

**Comment by kwquick** [comment]
This message is not being sent to your actor directly.  When the `createActor()` is called and the requested actor should be created on another system, the Thespian systems send this message the other system to request creation of the actor.

**Comment by pjz** [comment]
...so why is this being logged when there's only one ActorSystem involved?

**Comment by kwquick** [comment]
This message is also used when an external element calls `ActorSystem().createActor()`.  Because the external element is not a part of the Actor System itself, it needs to make a PendingActor request so that the Actor System will create the Actor on its behalf.

My guess is that:
a) your external code is repeatedly calling `ActorSystem(...).createActor(...)`
b) an existing actor is calling createActor with requirements that don't match the current system (although the logging you show above indicates "None", which should match anywhere) or where the target Actor class' `actorSystemCapabilityCheck()` is returning `False`
c) you have unsatisfiable requirements or capability check results in combination with (a) above.

If you'd like to provide some sample code (either here or privately) I'd be happy to help you diagnose this further.

**Comment by pjz** [comment]
Could it be the ActorSystem trying to restart a dead Actor, and announcing it?

**Comment by pjz** [comment]
Nevermind, I've got it solved.  It was an external command (CLI) trying to retrieve some data.  Thanks for the help!
