### ISSUE TITLE
Docker and Kubernetes cluster support

### ISSUE THREAD

**Issue by chaitanya9186** [godaddy/Thespian#45]
Is there any way I can make a thespian cluster running through docker and kubernetes?

Please provide any examples.

Thanks in advance

**Comment by kquick** [comment]
Hi,

You can use the thespian.director to start and configure a newly
provisioned node.  The `python -m thespian.director start` can be
executed via one of your init scripts.  Type `python -m
thespian.director` with no arguments to see help information.

Thespian can be especially useful in these configurations as well
because the docker or kubernetes base image only needs to contain
thespian itself, along with a configuration that specifies an external
Convention Leader to communicate with when it is started.  All of the
actual Actor code will be provided via the Convention Leader (which
should be the ingress node for the requests).

Regards,
  Kevin

chaitanya9186 writes:

> Is there any way I can make a thespian cluster running through docker
> and kubernetes?
> Please provide any examples.
> Thanks in advance

**Comment by kwquick** [comment]
Hi @chaitanya9186,

I'm closing this issue for now, but if you have additional questions or problems, please feel free to open a new issue at https://github.com/kquick/Thespian/issues.

Regards,
  Kevin
