### ISSUE TITLE
Hashable ActorAddress

### ISSUE THREAD

**Issue by davinellulinvega** [godaddy/Thespian#46]
Dear Sir,

This is much an issue, but rather a question.
In the implementation of the ActorAddress, I saw that the __hash__ function has been overridden and simply returns a hash of None for all ActorAddress instances. Making is effectively impossible to use an ActorAddress as a key for a dictionary or even insert it into a set.
I was wondering if it was possible to provide another hash function based on the content of `aaddr` so that addresses could be used in dictionaries and sets? It is not really a deal breaker if it is not possible, but would make keeping track of child actors much simpler.

Sincerely.

**Comment by kquick** [comment]
Hi @davinellulinvega,

The reason that an ActorAddress is not hashable is because it might internally mutate over time.  The mutation is entirely internal so an ActorAddress value will remain valid for the entire time you use it.  More details on this mutation are provided below, but despite the mutability, the ActorAddress *comparison* (e.g. `==` or `!=`) will work correctly at all times.  However, in Python, hashability is based on an explicit constant value rather than an equality comparision which is why they cannot be used this way.

Instead of storing the ActorAddress in a `set` or `dict` which requires `hash()` values, you can use a list of tuples.  This is actually what Thespian does internally, using the `AssocList` object defined in thespian.system.utilis (if this is a useful object, let me know and I can look into promoting it to a documented first-class member of the API).

---More Details (skip if uninteresting)---

The initial ActorAddress that is supplied as a response to the `createActor()` call references a pending Actor creation.  The actual Actor creation is asynchronous, so the address returned by the `createActor` call is a "local" address.   Once the actual Actor is created and the address is confirmed, the ActorAddress is updated to reference that actual address.  Any variable containing the original "local" version of the address will compare equal to the updated Address due to overloading of the `__eq__` and `__ne__` operations, so there is no concern about needing to "refresh" local variables containing `ActorAddress` values.

**Comment by davinellulinvega** [comment]
You Sir do not disappoint. That is one complete answer. Thank you very much for taking the time to satisfy my curiosity.
Concerning the `AssocList` implemented internally, it is very similar to what I end up doing in most of my projects, which is to "map" an id to an `ActorAddress` and work with the id in the rest of the script.
In my opinion it would be interesting to promote this class and have it appear in the documentation. It would avoid having to rely on poorly implemented external mechanisms. And make thespian more "complete" in a sense.

Sincerely.
