### ISSUE TITLE
Fairness in multithreading

### ISSUE THREAD

**Issue by GeorgJung** [godaddy/Thespian#52]
Dear all,

I have the following setup: Actor A creates a child actor B and sends an init message. Upon receiving init, B sets some timeouts to itself and performs a series of periodic tasks until it exits.

Unfortunately, instead of delivering the init message to B, the scheduler gives all execution time to actor A. After sending off the init message to B, A sends a message to itself, receives it (so we are in another message handler now), displays a dialog via easygui, and hogs all execution time until the next action at the dialog is initiated (prompting messages to other actors and/or itself). Only then the init message gets delivered to B (often too late to run the periodic tasks).

How can I ensure (or at least increase the probability) that the delivery of init to B interleaves with the execution of A in a fair way? Is there a wait command that would prompt the scheduler to continue with other threads?

Thanks for any kind of help,
greetings to kwquick, highly appreciated your help in earlier issues,
Georg

**Comment by kquick** [comment]
Hi @GeorgJung,

The issue here is not really an issue of fairness in scheduling but more of a disparity between the "Actor" concept and process-based blocking I/O.  This latter approach seems to be adhered to especially by EasyGUI (from the doc page at http://easygui.sourceforge.net describing it: "EasyGUI is different from other GUI generators in that EasyGUI is NOT event-driven. Instead, all GUI interactions are invoked by simple function calls.").    Basically what this means is that EasyGUI perform blocking operations while the GUI is being shown, so nothing else occurs.

By contrast, the Actor Model has a different conceptual orientation: actors tend to be idle unless they receive a message which asks them to perform work; they are busy while performing that work and then become idle again.

Depending on which system base you are using in Thespian, the EasyGUI mode of operation can have varying effects:

  * simpleSystemBase - in this mode there are no threads or processes, and actors are simply executed sequentially as there are available messages to process. In this mode, as long as Actor A's `receiveMessage` runs without exiting, no other actor will be able to run and perform any work.

  * One of the multiproc bases - here each Actor is represented by a separate process, but that process is still single-threaded.  The effect here is that while the `receiveMessage` is running, the Actor cannot service the socket or queue it uses to communicate with other Actors, which can delay the send or receive of the message to B.

Clearly, it's not practical to assert that you can only use one model or the other, so there are a couple of recommendations for using blocking or long-running operations with Thespian Actors:

  1. Run the blocking process in its own Actor, and expect that actor to be relatively incommunicative with other Actors.

  2. For system bases that support it (e.g. multiprocTCPBase), if the blocking operation is actually waiting on a file descriptor for additional work, you can return that file descriptor to Thespian instead of performing the blocking wait and Thespian will deliver a message when there is data available for that descriptor (see http://thespianpy.com/doc/using.html#hH-94edef18-154e-4847-864f-027dff4f6e0a).  If you used a different GUI package that allowed the use of an external event waiting mechanism, this would integrate well with this mode.

  3. Run EasyGUI in a thread within the actor.  Although I don't normally like to suggest using threads because that is mixing two different concurrency schemes, it can be useful for libraries like EasyGUI that are implemented around a blocking methodology and don't provide an easy way to alter the behavior.

  4. Run the EasyGUI in the main application instead of an Actor.  Use the ActorSystem interface (e.g. `tell()`, `ask()`, and `listen()` to communicate with the Actors providing the asynchronous background functionality.

**Comment by GeorgJung** [comment]
Thanks for the fast answer. I should have added that I use `multiprocTCPBase` in this project. In `simpleSystemBase` I would of course not have expected any interleaving. I suspected easygui to be the culprit, but your analysis made things very clear now.

I guess I was hoping for a convenient `self.wait_a_few_secods` method that makes sure that my message to self is handled (or even just sent) after the message to the child actor was delivered. I realize that I can implement that through the help of `wakeupAfter` messages, but it's not going to be elegant.

Easygui will not be used in the life system.

Thanks again for your help! To the point as usual!

**Comment by kquick** [comment]
You're welcome!

Using `wakeupAfter` is a good idea as a workaround to allow messages to (probably) get delivered before dropping into blocking mode.  It is clearly not optimal due to the problems of how much time is needed and not solving any issues once blocking mode is entered, but it's a good workaround for the startup problem.  I'll update the documentation with a better discussion of this type of situation and add that as one of the approaches.
